apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ name }}-ingress # {"$ref":"#/definitions/io.k8s.cli.substitutions.ingress-name-value"}
  namespace: {{ namespace }} # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}

spec:
  rules:
  - host: {{ host }} # {"$ref":"#/definitions/io.k8s.cli.setters.host"}
    http:
      paths:
      - path: {{ path }} # {"$ref":"#/definitions/io.k8s.cli.setters.path"}
        backend:
          serviceName: {{ name }}-service # {"$ref":"#/definitions/io.k8s.cli.substitutions.service-name-value"}
          servicePort: {{ port }} # {"$ref":"#/definitions/io.k8s.cli.setters.port"}
